Added deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,58 +1,101 @@
-deploy:
+name: Build and Deploy Code Notes
 
-  needs: build
+on:
+  push:
+    branches:
+      - main
 
-  runs-on: ubuntu-latest
+jobs:
 
-  steps:
+  build:
 
-    - name: Checkout code
-      uses: actions/checkout@v4
+    runs-on: ubuntu-latest
 
-    - name: Copy docker-compose.yml to Hetzner
-      uses: appleboy/scp-action@v0.1.7
-      with:
-        host: ${{ secrets.HETZNER_HOST }}
-        username: ${{ secrets.HETZNER_USER }}
-        key: ${{ secrets.HETZNER_SSH_KEY }}
-        source: "docker-compose.yml"
-        target: "/opt/apps/code-notes"
+    steps:
 
-    - name: Deploy to Hetzner
-      uses: appleboy/ssh-action@v1.2.2
-      with:
-        host: ${{ secrets.HETZNER_HOST }}
-        username: ${{ secrets.HETZNER_USER }}
-        key: ${{ secrets.HETZNER_SSH_KEY }}
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-        script: |
-          cd /opt/apps/code-notes
+      - name: Login Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-          echo "Pulling latest images..."
+      - name: Build and Push Backend
+        uses: docker/build-push-action@v6
+        with:
+          context: ./backend
+          push: true
+          tags: |
+            phyriak/code-notes-backend:${{ github.sha }}
+            phyriak/code-notes-backend:latest
 
-          docker compose pull
+      - name: Build and Push Frontend
+        uses: docker/build-push-action@v6
+        with:
+          context: ./frontend
+          push: true
+          tags: |
+            phyriak/code-notes-frontend:${{ github.sha }}
+            phyriak/code-notes-frontend:latest
 
-          echo "Starting Code Notes..."
 
-          docker compose up -d
+  deploy:
 
-          echo "Waiting for application..."
+    needs: build
 
-          for i in {1..12}; do
-            if curl -f http://localhost:8085; then
-              echo "Code Notes is UP"
+    runs-on: ubuntu-latest
 
-              docker image prune -af
+    steps:
 
-              exit 0
-            fi
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-            echo "Application not ready yet..."
-            sleep 10
-          done
+      - name: Copy docker-compose.yml to Hetzner
+        uses: appleboy/scp-action@v0.1.7
+        with:
+          host: ${{ secrets.HETZNER_HOST }}
+          username: ${{ secrets.HETZNER_USER }}
+          key: ${{ secrets.HETZNER_SSH_KEY }}
+          source: "docker-compose.yml"
+          target: "/opt/apps/code-notes"
 
-          echo "Code Notes failed to start"
+      - name: Deploy to Hetzner
+        uses: appleboy/ssh-action@v1.2.2
+        with:
+          host: ${{ secrets.HETZNER_HOST }}
+          username: ${{ secrets.HETZNER_USER }}
+          key: ${{ secrets.HETZNER_SSH_KEY }}
 
-          docker compose ps
+          script: |
+            cd /opt/apps/code-notes
 
-          exit 1
+            echo "Pulling Docker images..."
+
+            docker compose pull
+
+            echo "Starting Code Notes..."
+
+            docker compose up -d
+
+            echo "Waiting for application..."
+
+            for i in {1..12}; do
+              if curl -f http://localhost:8085; then
+                echo "Code Notes is UP"
+
+                docker image prune -af
+
+                exit 0
+              fi
+
+              echo "Application not ready yet..."
+              sleep 10
+            done
+
+            echo "Code Notes failed to start"
+
+            docker compose ps
+
+            exit 1
