Added deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,4 +1,4 @@
-name: Deploy Code Notes
+name: Build and Deploy Code Notes
 
 on:
   push:
@@ -6,12 +6,46 @@ on:
       - main
 
 jobs:
-  deploy:
+  build:
+
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
+
+      - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Login Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: Build and Push Backend
+        uses: docker/build-push-action@v6
+        with:
+          context: ./backend
+          push: true
+          tags: |
+            phyriak/code-notes-backend:${{ github.sha }}
+            phyriak/code-notes-backend:latest
+
+      - name: Build and Push Frontend
+        uses: docker/build-push-action@v6
+        with:
+          context: ./frontend
+          push: true
+          tags: |
+            phyriak/code-notes-frontend:${{ github.sha }}
+            phyriak/code-notes-frontend:latest
+
+  deploy:
+
+    needs: build
+
+    runs-on: ubuntu-latest
+
+    steps:
 
       - name: Deploy to Hetzner
         uses: appleboy/ssh-action@v1.2.2
@@ -19,11 +53,35 @@ jobs:
           host: ${{ secrets.HETZNER_HOST }}
           username: ${{ secrets.HETZNER_USER }}
           key: ${{ secrets.HETZNER_SSH_KEY }}
+
           script: |
-            cd /opt/code-notes
+            cd /opt/apps/code-notes
 
-            git pull origin main
+            echo "Pulling latest images..."
 
-            docker compose up -d --build
+            docker compose pull
 
-            docker image prune -f
+            echo "Starting Code Notes..."
+
+            docker compose up -d
+
+            echo "Waiting for application..."
+
+            for i in {1..12}; do
+              if curl -f http://localhost:8085; then
+                echo "Code Notes is UP"
+
+                docker image prune -af
+
+                exit 0
+              fi
+
+              echo "Application not ready yet..."
+              sleep 10
+            done
+
+            echo "Code Notes failed to start"
+
+            docker compose ps
+
+            exit 1
