Added deploy script

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,87 +1,58 @@
-name: Build and Deploy Code Notes
+deploy:
 
-on:
-  push:
-    branches:
-      - main
+  needs: build
 
-jobs:
-  build:
+  runs-on: ubuntu-latest
 
-    runs-on: ubuntu-latest
+  steps:
 
-    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
 
-      - name: Checkout code
-        uses: actions/checkout@v4
+    - name: Copy docker-compose.yml to Hetzner
+      uses: appleboy/scp-action@v0.1.7
+      with:
+        host: ${{ secrets.HETZNER_HOST }}
+        username: ${{ secrets.HETZNER_USER }}
+        key: ${{ secrets.HETZNER_SSH_KEY }}
+        source: "docker-compose.yml"
+        target: "/opt/apps/code-notes"
 
-      - name: Login Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Deploy to Hetzner
+      uses: appleboy/ssh-action@v1.2.2
+      with:
+        host: ${{ secrets.HETZNER_HOST }}
+        username: ${{ secrets.HETZNER_USER }}
+        key: ${{ secrets.HETZNER_SSH_KEY }}
 
-      - name: Build and Push Backend
-        uses: docker/build-push-action@v6
-        with:
-          context: ./backend
-          push: true
-          tags: |
-            phyriak/code-notes-backend:${{ github.sha }}
-            phyriak/code-notes-backend:latest
+        script: |
+          cd /opt/apps/code-notes
 
-      - name: Build and Push Frontend
-        uses: docker/build-push-action@v6
-        with:
-          context: ./frontend
-          push: true
-          tags: |
-            phyriak/code-notes-frontend:${{ github.sha }}
-            phyriak/code-notes-frontend:latest
+          echo "Pulling latest images..."
 
-  deploy:
+          docker compose pull
 
-    needs: build
+          echo "Starting Code Notes..."
 
-    runs-on: ubuntu-latest
+          docker compose up -d
 
-    steps:
+          echo "Waiting for application..."
 
-      - name: Deploy to Hetzner
-        uses: appleboy/ssh-action@v1.2.2
-        with:
-          host: ${{ secrets.HETZNER_HOST }}
-          username: ${{ secrets.HETZNER_USER }}
-          key: ${{ secrets.HETZNER_SSH_KEY }}
+          for i in {1..12}; do
+            if curl -f http://localhost:8085; then
+              echo "Code Notes is UP"
 
-          script: |
-            cd /opt/apps/code-notes
+              docker image prune -af
 
-            echo "Pulling latest images..."
+              exit 0
+            fi
 
-            docker compose pull
+            echo "Application not ready yet..."
+            sleep 10
+          done
 
-            echo "Starting Code Notes..."
+          echo "Code Notes failed to start"
 
-            docker compose up -d
+          docker compose ps
 
-            echo "Waiting for application..."
-
-            for i in {1..12}; do
-              if curl -f http://localhost:8085; then
-                echo "Code Notes is UP"
-
-                docker image prune -af
-
-                exit 0
-              fi
-
-              echo "Application not ready yet..."
-              sleep 10
-            done
-
-            echo "Code Notes failed to start"
-
-            docker compose ps
-
-            exit 1
+          exit 1
